### ISSUE TITLE
MacBook Pro gets hot after a few mins of running the emulator

### ISSUE THREAD

**Issue by ijean** [astralaster/agon-light-emulator#12]
Hi,

great work with the Agon emulator, it looks great for now and I was able to build it without problems on my MacBook Pro M1.
I noticed that after a few minutes of usage my Mac gets super hot and I have to stop the emulator. Any idea what could cause this problem ? (BTW, same problem with the emulator built in debug and release mode)

Thanks,
Jean

**Comment by astralaster** [comment]
Thanks for your feedback. Unfortunately this behaviour is to be expected at the moment. The emulator uses two cores at 100% while running at maximum speed. We already have ideas how to limit the speed to the real agon and then cpu load will decrease, too. But our current scope is feature completeness at VDP 1.03 level. After we have achieved this, we will add more QOL features like this.

**Comment by guidol70** [comment]
OK ;) I will aso wait for the net release - got the emulator running under Linux Mint 21.1 on a HP Chromebox Celeron DualCore 2955U at 1.4Ghz and also got the 2 Cores at 100%
Is there for another keyboard-layout (de/german)?

**Comment by astralaster** [comment]
@guidol70 More keyboard layouts will follow. Currently only us keyboard layout is available.
