### ISSUE TITLE
VDP command get pixel colour doesn't return expected results.

### ISSUE THREAD

**Issue by pgregory** [astralaster/agon-light-emulator#20]
When using the VDP command "23, 0, $84, x; y;" in the emulator, in mode 2 (320x200), I don't get the expected results back. I'm getting some data back, much of the screen is black, with some white and some green pixels, and I know my coordinates are correct as I'm using the same coordinates to position a sprite, but the return from this command is off. I sometimes get a green pixel back, but nowhere where I'd expect it to be. Could it be that the change of mode is causing some issues with the canvas?

**Comment by astralaster** [comment]
Fixed in v0.5.0.
