### ISSUE TITLE
Make RST be less picky about .LIS vs .LIL suffixes

### ISSUE THREAD

**Issue by lennart-benschop** [astralaster/agon-light-emulator#4]
This is one for the upstream component, but you probably know how to pass it on.

My FORTH for Agon uses RST.LIL in 16-bit mode (ADL=0) and this is rejected by the eZ80 interpreter.  The hardware just works. There may be other programs that refuse to run just because the wrong instruction suffix (in fact a prefix byte in the binary machine code) is used on RST.

**Comment by astralaster** [comment]
I think this is already fixed upstream: https://github.com/tomm/ez80/commit/148aae0ee1705231b06a6ae41dff4d97149ce75b

**Comment by lennart-benschop** [comment]
Need to update your Cargo.toml file for the correct git rev of iz80. 
But FORTH runs. And I can load up tetris,4th, which is already somewhat playable.

**Comment by astralaster** [comment]
Oh sorry, I've misread the parent commit hash as the commit hash in the ez80 commit and thought its already in there. But great to hear that your problem is fixed.

**Comment by lennart-benschop** [comment]
Anyway, FORTH runs now, but the nano editor gets a message for RST.LIS in ADL mode (and it does not execute that call then). In this mode it would need to be .LIL, but the macro defined in mos_api.inc has an RST.LIS instead. Andain this just works on the real hardware.

**Comment by lennart-benschop** [comment]
When I hack this locally, It will get nano to execute, even though it is not really usable at this state, but getting closer.
